## 1. Promise 的含义

`Promise` ，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。**从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。**

`Promise` 对象有以下两个特点:

1. 对象的状态不受外界影响。`Promise`对象代表一个异步操作，有三种状态：`pending`（进行中）、`fulfilled`（已成功）和`rejected`（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。
2. 一旦状态改变，就不会再变，任何时候都可以得到这个结果。`Promise`对象的状态改变，只有两种可能：从`pending`变为`fulfilled`和从`pending`变为`rejected`。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对`Promise`对象添加回调函数，也会立即得到这个结果。

`Promise` 也有一些缺点：

1. `Promise` 无法取消，一旦新建它就会立即执行，无法中途取消。
2. 如果不设置回调函数，`Promise` 内部抛出的错误，不会反应到外部。
3. 当处于 `pending` 状态时，无法得知目前进展到哪一阶段（刚刚开始还是即将完成）。

## 2. 基本用法

1. 创建

   使用 `Promise` 构造函数，生成 `Promise` 实例。

   ```javascript
   const promise = new Promise(function(resolve, reject) {
     // ... some code

     if (/* 异步操作成功 */){
       resolve(value);
     } else {
       reject(error);
     }
   });
   ```

2. Promise 新建后就会立即执行

   ```javascript
   let promise = new Promise(function(resolve, reject) {
     console.log('Promise');
     resolve();
   });

   promise.then(function() {
     console.log('resolved.');
   });

   console.log('Hi!');

   // Promise
   // Hi!
   // resolved
   ```

3. 调用 resolve 或 reject 并不会终结 Promise 的参数函数的执行。

   ```javascript
   new Promise((resolve, reject) => {
     resolve(1);
     console.log(2);
   }).then(r => {
     console.log(r);
   });
   // 2
   // 1
   ```

## 3. 实例方法

1. Promise.prototype.then(): 为 Promise 实例添加状态改变时的回调函数

2. Promise.prototype.catch(): 是 `.then(null, rejection)` 或 `.then(undefine, rejection)` 的别名，用于指定发生错误时的回调函数。

   > 如果没有使用 `catch` 方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码
   >
   > ```javascript
   > const someAsyncThing = function() {
   >   return new Promise(function(resolve, reject) {
   >     // 下面一行会报错，因为x没有声明
   >     resolve(x + 2);
   >   });
   > };
   >
   > someAsyncThing().then(function() {
   >   console.log('everything is great');
   > });
   >
   > setTimeout(() => { console.log(123) }, 2000);
   > // Uncaught (in promise) ReferenceError: x is not defined
   > // 123
   > ```
   >
   > 上面代码中，`someAsyncThing`函数产生的 Promise 对象，内部有语法错误。浏览器运行到这一行，会打印出错误提示`ReferenceError: x is not defined`，但是不会退出进程、终止脚本执行，2 秒之后还是会输出`123`。**这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。**

3. Promise.prototype.finally(): ES2018 引入标准的，用于指定不管 `Promise` 对象最后状态如何，都会执行的操作。

   ```javascript
   server.listen(port)
     .then(function () {
       // ...
     })
     .finally(server.stop);
   ```

   `finally`方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是`fulfilled`还是`rejected`。这表明，`finally`方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。

## 4. 静态方法

1. Promise.all(): 用于将多个 Promise 实例，包装成一个新的 Promise 实例。

2. Promise.race(): 将多个 Promise 实例，包装成一个新的 Promise 实例。只要一个 Promise 实例率先改变状态，就改变状态。

3. Promise.allSettled(): ES2020 引入，接受一组 Promise 实例作为参数，包装成一个新的 Promise 实例。只有等到所有这些参数实例都返回结果，不管是`fulfilled`还是`rejected`，包装实例才会结束。该方法返回的新的 Promise 实例，一旦结束，状态总是`fulfilled`，不会变成`rejected`。

   ```javascript
   const resolved = Promise.resolve(42);
   const rejected = Promise.reject(-1);

   const allSettledPromise = Promise.allSettled([resolved, rejected]);

   allSettledPromise.then(function (results) {
     console.log(results);
   });
   // [
   //    { status: 'fulfilled', value: 42 },
   //    { status: 'rejected', reason: -1 }
   // ]
   ```

4. Promise.resolve(): 将现有对象转为 Promise 对象。

5. Promise.reject(): 返回一个新的 Promise 实例，该实例的状态为 `rejeted`。

   > **注意：Promise.reject() 方法的参数，会原封不动地作为 reject 的理由，变成后续方法的参数。这一点与 `Promise.resolve` 方法不一致。**

   ​







