## 1. 含义

ES2017 标准引入了 async 函数，使得异步操作变得更加方便。**async 函数就是 Generator 函数的语法糖。**

```javascript
// Generator 函数写法
const fs = require('fs');

const readFile = function(fileName) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fileName, function(error, data)) {
      if (error) return reject(error);
      resolve(data);
    }
  })
}

const gen = function* () {
  const f1 = yield readFile('/etc/fstab');
  const f2 = yield readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
}

// async 函数写法
const asyncReadFile = async function() {
  const f1 = await readFile('/etc/fstab');
  const f2 = await readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
}
```

一比较就会发现，`async` 函数就是将 Generator 函数的星号（`*`）替换成 `async` ，将 `yield` 替换成 `await`，仅此而已。

`async` 函数对 Generator 函数的改进，体现在以下四点：

1. 内置执行器

   Generator 函数的执行必须靠执行器，所以才有了 `co` 模块，而 `async` 函数自带执行器。也就是说，`async` 函数的执行，与普通函数一模一样，只要一行。

   ```javascript
   // 直接调用函数，然后就会自动执行，输出最后结果
   // Generator 函数，需要调用 next 方法，或者用 co 模块，才能真正执行，得到最后结果。
   asyncReadFile();
   ```

2. 更好的语义

   `async` 和 `await`，比起星号和 `yield`，语义更清楚了。`async` 表示函数里有异步操作，`await` 表示紧跟在后面的表达式需要等待结果。

3. 更广的适用性

   `co` 模块约定，`yield` 命令后面只能在 Thunk 函数 或 Promise 对象，而 `async` 函数的 `await` 命令后面，可以是 Promise 对象和原始类型的值（数值、字符串和布尔值，但这时会自动转成立即 resolved 的Promise 对象）。

4. 返回值是 Promise

   `async` 函数的返回值是 Promise 对象，这比 Generator 函数的返回值是 Iterator 对象方便多了。

**进一步说，`async` 函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而 `await` 命令就是内部 `then` 命令的语法糖**

## 2. 基本用法

async 函数返回一个 Promise 对象，当函数执行的时候，一旦遇到 `await` 就会先返回，等到异步操作完成，再接着执行函数体内后面的语句

```javascript
// 函数声明
async function foo() {}

// 函数表达式
const foo = async function () {};

// 对象的方法
let obj = { async foo() {} };
obj.foo().then(...)

// Class 的方法
class Storage {
  constructor() {
    this.cachePromise = caches.open('avatars');
  }

  async getAvatar(name) {
    const cache = await this.cachePromise;
    return cache.match(`/avatars/${name}.jpg`);
  }
}

const storage = new Storage();
storage.getAvatar('jake').then(…);

// 箭头函数
const foo = async () => {};
```

## 3. 语法

async 函数的语法规则总体上比较简单，**难点是错误处理机制。**

1. 返回 Promise 对象

   ```javascript
   // async 函数内部 return 语句返回的值，会成为 then 方法
   async function f() {
     return 'hello world';
   }

   f().then(v => console.log(v));

   // async 函数内部抛出错误，会导致返回的 Promise 对象变成 reject 状态。抛出的错误会被 catch 方法回调函数接收到。
   async function f() {
     throw new Error('出错了')；
   }

   f().then(
     v => console.log(v),
     e => console.log(e)
   )
   // Error: 出错了
   ```

2. Promise 对象的状态变化

   `async` 函数返回的 Promise 对象，必须等到内部所有 `await` 命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到 `return` 语句或者抛出错误。**也就是说，只有 `async` 函数内部的异步操作执行完，才会执行 `then` 方法指定的回调函数**

   ```javascript
   async function getTitle(url) {
     let response = await fetch(url);
     let html = await response.text();
     return html.match(/<title>([\s\S]+)<\/title>/i)[1];
   }
   getTitle('https://tc39.github.io/ecma262/').then(console.log)
   // "ECMAScript 2017 Language Specification"
   ```

3. await 命令

   正常情况下，`await` 命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。

   ```javascript
   async function f() {
     // 等同于
     // return 123;
     return await 123;
   }

   f().then(v => console.log(v)) // 123
   ```

   另一种情况，`await` 命令后面是一个 `thenable` 对象（即定义 `then` 方法的对象），那么 `await` 会将其等同于 Promise 对象

   ```javascript
   class Sleep {
     constructor(timeout) {
       this.timeout = timeout;
     }
     then(resolve,reject) {
       const startTime = Date.now();
       setTimeout(
         () => resolve(Date.now() - startTime),
         this.timeout
       );
     }
   }

   (async () => {
     const sleepTime = await new Sleep(1000);
     console.log(sleepTime);
   })();
   // 1000
   ```

   任何一个 `await` 语句后面的 Promise 对象变成 `reject` 状态，那么整个 `async` 函数都会中断执行

   ```javascript
   async function f() {
     await Promise.reject("出错了");
     await Promise.resolve('hello world'); // 这里不会执行
   }

   // 也可以将第一个 await 放在 try...catch 结构里面，这样即使前一个异步操作失败，也不会中断后面的异步操作
   async function f() {
     try {
       await Promise.reject('出错了');
     } catch(e) {}
     
     return await Promise.resolve('hello world');
   }

   f().then(v => console.log(v))
   // hello world

   // 也可以在 await 后面的 Promise 对象再跟一个 catch 方法，处理前面可能出现的错误
   async function f() {
     await Promise.reject('出错了')
     	.catch(e => console.log(e));
     return await Promise.resolve('hello world')；
   }

   f()
   .then(v => console.log(v)); 
   // 出错了
   // hello world
   ```

4. 错误处理

   如果 `await` 后面的异步操作出错，那么等同于 `async` 函数返回的 Promise 对象被 `reject`。

   ```javascript
   async function f() {
     await new Promise(function (resolve, reject) {
       throw new Error('出错了')；
     })
   }

   f()
   .then(v => console.log(v))
   .catch(e => console.log(e))
   // Error: 出错了
   ```

   防止出错的方法，也是将其放在 `try...catch` 代码块之中。

5. 使用注意点

   * `await` 命令后面的 `Promise` 对象，运行结果可能是 `rejected`，所以最好把 `await` 命令放在 `try...catch` 代码块中。

   * 多个 `await` 命令后面的异步操作，如果不存在继发关系，最好让它们同时触发。

     ```javascript
     // 这是两个独立的异步操作（即互不依赖）- 完全可以让它们同时触发
     let foo = await getFoo();
     let bar = await getBar();

     // 写法一
     let [foo, bar] = await Promise.all([getFoo(), getBar()]);

     // 写法二
     let fooPromise = getFoo();
     let barPromise = getBar();
     let foo = await fooPromise;
     let bar = await barPromise;
     ```

   * `await` 命令只能用在 `async` 函数之中，如果用在普通函数，就会报错

   * async 函数可以保留运行堆栈

     ```javascript
     // b() 运行的时候，a()是暂停执行，上下文环境都保存着。一旦b()或c()报错，错误堆栈将包括a()
     const a = async () => {
       await b();
       c();
     }
     ```

## 4. async 函数的实现原理

```javascript
// async 实现原理，就是将 Generator 函数和自动执行器，包装在一个函数里
async function fn(args) {
  // 函数体
}

// 等同于
function fn(args) {
  return spawn (funciont* () {
    // 函数体
  })
}
// spawn 函数：自动执行器
function spawn(genF) {
  return new Promise((resolve, reject) => {
    // 生成遍历器
    const gen = genF();
    // 递归遍历遍历器
    function step(nextF) {
      let next;
      try {
        next = nextF();
      } catch (e) {
        return reject(e);
      }
      // 遍历结束时
      if (next.done) {
        return resolve(next.value);
      }
      Promise.resolve(next.value).then(v => {
        step(function() { return gen.next(v); })
      }, e => {
        step(function() { return gen.throw(e); })
      })
    }
    
    // 启动遍历器
    step(function() { return gen.next(undefined); });
  })
}
```

## 5.  相关应用

见文档







